name: Dev - PR Open

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build_changelog:
    name: Build Changelog
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ORG_PAT }}
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Get Package Version
        id: version
        run: pnpm pkg get version --workspaces=false | tr -d \"
      - name: Pring Package Version
        run: echo ${{ steps.version.outputs.version }}
      - name: Run Changelog Builder
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: changelog-config.json

  add_comment:
    name: Add Comment
    permissions: 'write-all'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Add Comment
        uses: mshick/add-pr-comment@v2.8.2
        with:
          message: Please set a versioning label of either `major`, `minor`, or `patch` to the pull request. https://semver.org/
          repo-token: ${{ secrets.GITHUB_TOKEN }}
