name: Dev - PR Label Check

on:
  pull_request:
    types: [reopened, labeled, unlabeled]
    branches:
      - main

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  label_check:
    name: Check PR Labels
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Check PR Label
        uses: mheap/github-action-required-labels@v5.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: exactly
          count: 1
          labels: 'major, minor, patch'
