name: Changelog Generator

on:
  push:
    tags:
      - 'v*'

jobs:
  changelog:
    name: Changelog
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Check-out
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets. }}

      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1.4.0

      - name: Generate release changelog
        id: generate-release-changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.4
        with:
          token: ${{ secrets.GH_ORG_PAT }}
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: true

      - name: Commit updates
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          commit_message: ChangelogÏ ${{ steps.previoustag.outputs.tag }} [skip-ci]
          file_pattern: CHANGELOG.md package.json
          branch: main
          push_options: '--force'
          

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: changelog
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: 'Get Previous tag'
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1.4.0

      - name: Get last changelog entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2.2.3
        with:
          version: ${{ steps.previoustag.outputs.tag }}
          path: ./CHANGELOG.md

      - name: Create Release
        id: create_release
        uses: elgohr/Github-Release-Action@20240405193535
        with:
          title: ${{ steps.changelog_reader.outputs.version }}
