name: Pull Request Formatting

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled, closed]
    branches:
      - main

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  fail-by-label:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Label checker for pull requests
        uses: agilepathway/label-checker@v1.6.32
        with:
          one_of: 'major,minor,patch'
          none_of: 'draft'
          repo_token: ${{ secrets.GITHUB_TOKEN }}
